name: financial_management
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.19.0
  uuid: ^3.0.6

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.2.1
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/avatar.png
